MapsActivity.kt and MapActivity.java
#7
- if I call search places and I do not choose any place I have got
IllegalArgumentException: Parameter specified as non-null is null in
- solved to get null safe to data parameter